services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - ./data/db/mongodb:/data/db
    environment:
      - MONGO_INITDB_DATABASE=parkesase
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - TZ=America/Sao_Paulo
    ports:
      - 27017:27017
    networks:
      - mongo-network

  mongo-express:
    container_name: mongo-express
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=secret
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=pass
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - TZ=America/Sao_Paulo
    networks:
      - mongo-network
    depends_on:
      - mongodb

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - ./data/db/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=myuser
      - TZ=America/Sao_Paulo
    ports:
      - 5432:5432
    networks:
      - postgres-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
      - TZ=America/Sao_Paulo
    ports:
      - 5050:80
    networks:
      - postgres-network
    depends_on:
      - postgres

  java:
    container_name: java
    image: maven:3.8.4-openjdk-17
    volumes:
      - ./:/app
    working_dir: /app
    command: bash -c "mvn clean install && java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -jar target/ParkEase.jar"
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - 8080:8080
      - 5005:5005
    networks:
      - mongo-network
      - postgres-network
    depends_on:
      - mongodb
      - postgres

networks:
  postgres-network:
      name: postgres-network
  mongo-network:
      name: mongo-network